destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/wiki-pdf"
port: 4010
output: pdf
product: wiki
print_title: Jekyll theme for documentation â€” wiki product
print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: wiki_sidebar
